### ISSUE TITLE
Set up IRC

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock-Project#10]
Configure the IRC channel properly.

**Comment by GenPage** [comment]
Discuss about Op/Voice/Members. Maybe GH team members be voiced?

**Comment by Olympic1** [comment]
Give op status to the important people (server hosts, owners, lead dev), and give voice to the others from the GH team.

And it's always handy to add a bot to the channel

**Comment by ghost** [comment]
@ThomasKerman Can you get the IRC bot to work for this repo, as well?

**Comment by Olympic1** [comment]
Closing as everyone got their Op/Voice status and the bot was configured

**Comment by TN-1** [comment]
I didnt get voice

**Comment by NecroBones** [comment]
I can connect and type, dunno if I need anything else. ;)

**Comment by TN-1** [comment]
True that :p
