### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by StollD** [KSP-SpaceDock/SpaceDock-Project#11]
We need a new Icon for SpaceDock, I wouldn't continue to use the old one, if we already change the name. Maybe a little spacedock that orbits a planet, and that with some kind of comic style? Also, I would like to suggest a little color change (green bar at the top), to make it a) different from KerbalStuff and b) to align with the Space\* name. Maybe use something like a dark blue?

As my graphical skill are below Int32.MinValue, we would need someone to do this job. Any ideas?

---
#### Current design options:

**sharksharkco - Maintenance Page**
http://i.imgur.com/MvlGupK.gif

**sharksharkco - Logo Designs**
http://sktk.us/db/RoundOne.png
http://sktk.us/db/RoundTwo-OptB-v2.png
http://sktk.us/db/RoundThree-OptB.png
http://sktk.us/db/RoundFour-OptB.png
http://sktk.us/db/RoundFour-Optb-Colors.png
http://sktk.us/db/Fontchoices.png
http://sktk.us/db/V5.png

**Unknown601 - Logo Designs**
http://imgur.com/a/ZT73Y

**Comment by sharksharkco** [comment]
I'd be happy to help out. I'll draw a few things up

**Comment by NecroBones** [comment]
I can try drawing some things up too.   EDIT: I probably won't have time right away though, so don't let me hold anyone up.

**Comment by sharksharkco** [comment]
I'd say more the merrier, quick vote if needed. Badabing

**Comment by inigma2** [comment]
http://i.imgur.com/MvlGupK.gif Kerbal at work. recommended for maintenance page. courtesy sharksharkco

**Comment by ghost** [comment]
A logo for the whole organization would be cool to have, too.

**Comment by inigma2** [comment]
logo needs to be kerbally somehow. i suggested jeb in foreground, space station in back ground orbiting planet.  Thomas suggested just a spacedock in orbit.

**Comment by inigma2** [comment]
perhaps a Rune-style wheel space station with stock parts?

**Comment by sharksharkco** [comment]
@phmayo SpaceDock is the relaunch, right? What's the organization - KS Reborn?

**Comment by sharksharkco** [comment]
@inigmatus love the rune idea, put a little POWA behind it

**Comment by inigma2** [comment]
http://i.imgur.com/uyZ2AVU.png one example... we'd have to get permission of course. Let me hit him up for that.

**Comment by inigma2** [comment]
pm posted. wait and see. He's in Spain so hopefully I've caught him in time.

**Comment by inigma2** [comment]
u know, I did make this at one time: http://i.imgur.com/tG2o9rE.png

and http://i.imgur.com/y8xwyd7.png

**Comment by GenPage** [comment]
A logo like NASA or PASA with @inigmatus example of a space station would be :+1:

[NASA example](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/1237px-NASA_logo.svg.png)
[PSAS example](https://avatars0.githubusercontent.com/u/3676826?v=3&s=200)

**Comment by sharksharkco** [comment]
Nice, I was thinking along those lines too! I'm cooking a few up right now i'll post a board of a few options in an hr or two.

**Comment by sharksharkco** [comment]
My focus has been SpaceDock atm, what's the organization part?

**Comment by GenPage** [comment]
I think that requires more input/discussion. Should the overall org name still be KerbalStuff-Reborn? I do not really think so. While the application is SpaceDock, I believe the org name should be something else. @phmayo

**Comment by sharksharkco** [comment]
Gotcha. KerbalStuff Reborn Collective - KSRC an idea

**Comment by ghost** [comment]
@GenPage: The organization is KSP-SpaceDock. The repo is KS-REborn, but we should sunset this once we are going.

**Comment by inigma2** [comment]
Rune has given us permission for any of these:

http://imgur.com/a/Lyhzk

**Comment by sharksharkco** [comment]
Got held up a bit at work didn't get to concentrate as much as I wanted to, worked on a few quick concepts/colors, going to spend more time after work and incorporate a circular 'badge' direction one as well. Any thoughts are welcome.
http://sktk.us/db/RoundOne.png

**Comment by NecroBones** [comment]
Nice! That's a great start, I like those. I tried one simple design so far and it turned out awful. :)

**Comment by sharksharkco** [comment]
Here's a progress pic on one concept,
http://sktk.us/db/RoundTwo-OptB-v2.png

**Comment by Olympic1** [comment]
Very nice and we can use the left side as icon

**Comment by bgse** [comment]
@sharksharkco The middle one from RoundOne is a very good idea imho.

**Comment by ILM126** [comment]
@sharksharkco That is a good looking design :+1:

**Comment by NecroBones** [comment]
@sharksharkco Thumbs up for sure!

**Comment by sharksharkco** [comment]
Here's an updated concept bit cleaned up with two shape options and the blank option, and one example of a color scheme paired with it (for the site) 

http://sktk.us/db/RoundThree-OptB.png

**Comment by kaptain-kavern** [comment]
Hey nice logos @sharksharkco! I like the C. With the little Rocket ;-)

**Comment by TN-1** [comment]
Nice work! I too like C

**Comment by Olympic1** [comment]
idem

**Comment by StollD** [comment]
I also support Nr.3. If VITAS has no problems with it, we should use it as the official Icon / Logo.

**Comment by inigma2** [comment]
I like C as well.

**Comment by Ristellise** [comment]
C will be my choice too... would prefer 2 ships docking as an option...

**Comment by sebneira** [comment]
@sharksharkco Could you try a version without the dots inside the trail? I feel the asymmetry there is not helping on the overall feel.

Other than that, really good work!

**Comment by sharksharkco** [comment]
Hey everyone, thanks for the comments! I'll throw out a round four this afternoon with a few more options/tightening things up, possibly one more color combination. 

I made a quick screenshot of how that color/logo combo may be applied to the current header, http://sktk.us/db/Screen%20Shot%202016-02-16%20at%2011.04.56%20PM.png

**Comment by StollD** [comment]
While I like the logo, I don't think that the gradient fits very well. I would rather like to keep the solid color. Also, we should probably consider doing just a logo, without the name, as the name is already there (which can be changed though)

**Comment by inigma2** [comment]
i like the gradient, but only if it was reversed dark to purple or just mostly the blue and less purple. the logo and name should be separate graphics so either can be used.

**Comment by NecroBones** [comment]
That's a good point, I'm assuming the logo has transparency to sit over the gradient? That would be ideal. I like the gradient, but I'm good with other colors too. Either way. :)

**Comment by sharksharkco** [comment]
Whatever the final design is I'm going to create a whole collection of assets; from horizontal to vertical configurations, to just the emblem, just the text, svg version, high-res print version, icons, a flag for KSP. Hell I'll even separate the colors for screen-printing. The wyrks.

I can find a font that would be similar so we can use live text, although using an image is absolutely fine.
https://googlewebmastercentral.blogspot.com/2013/05/using-schemaorg-markup-for-organization.html
I like the font, this way we're also branding SpaceDock a bit further.

I'll toss a few more background ideas out as well this afternoon.

**Comment by inigma2** [comment]
I'm adding sharksharkco to the roster as Graphics Designer

**Comment by inigma2** [comment]
also, any possible way we could incorporate these into possible rotating backgrounds either on the main page or fail pages?

http://i.imgur.com/jdclbZN.png  - Circular Station and Ship by Rune
http://i.imgur.com/y8xwyd7.png - ISS-type station and stock Space Shuttle by inigma

**Comment by sharksharkco** [comment]
Hey everyone, I've touched on some of your comments in this next round. Also worked on some different color combinations.

http://sktk.us/db/RoundFour-OptB.png
http://sktk.us/db/RoundFour-Optb-Colors.png

**Comment by ILM126** [comment]
C, D, or F for Option B
And for the colour option, blue.

**Comment by Ristellise** [comment]
Color is blue
I liked the last one. Looks like a station. With a rocket docking it.

**Comment by TN-1** [comment]
F and blue or the first purple.  
Very nice work @sharksharkco!

**Comment by kaptain-kavern** [comment]
C/F and blue for me too :+1:

**Comment by inigma2** [comment]
F and blue here.

**Comment by NecroBones** [comment]
Man, they all look nice. I think I like F the best though. And on colors, I think I like blue the best, but I'd say my least favorite is the bright non-gradient orange. All of the others look pretty good to me.

**Comment by sharksharkco** [comment]
Alright I think we're getting there! Here are some font choices
http://sktk.us/db/Fontchoices.png

**Comment by DuoDex** [comment]
I think those look a little busy for logos, KS's was very recognizable without being too detailed. Let me try and whip something up myself.

**Comment by sharksharkco** [comment]
Here's a simpler one too http://sktk.us/db/V5.png
could loose the ship even further

**Comment by DuoDex** [comment]
Can you give an Inkscape file of that? I'd like to mess with it further because it looks so good :+1:

**Comment by ghost** [comment]
OK here is my ever expanding logo idea page
coming next 3D rendered station! http://imgur.com/a/ZT73Y

**Comment by inigma2** [comment]
Wanted to add http://i.imgur.com/MvlGupK.gif as a temp maintenance gif asset if ever needed.

**Comment by inigma2** [comment]
inigma's KISS approach to logo design: http://i.imgur.com/R461qxa.jpg

**Comment by sharksharkco** [comment]
Hi everyone, we've entered the final round for logos. Please vote from this selection! (hover or click image to get name)
https://cloud.52k.de/index.php/apps/galleryplus/s/MNNgLfiUSMEhyJb#

Enter your vote here!

**Comment by godarklight** [comment]
I like sharkshark-b

**Comment by StollD** [comment]
I vote for SharkShark-B too

**Comment by V1TA5** [comment]
im going with VITAS-3

**Comment by sharksharkco** [comment]
I vote SharkShark-B

**Comment by inigma2** [comment]
I like VITAS-1 aka logo-1, simple elegant, has a pic for the logo, distinct from KS style, and not copyright-prone like my docking port one.

**Comment by FrikFry** [comment]
:+1: SharkShark-B

**Comment by GenPage** [comment]
:+1: SharkShark-B

**Comment by Olympic1** [comment]
SharkShark-B

**Comment by overcookedTOFU** [comment]
SharkShark-B looks great to me!

**Comment by NecroBones** [comment]
SharkShark-B looks good to me.

**Comment by rkarmark** [comment]
Sharkshark-b is nice

**Comment by ghost** [comment]
OK a added more to my logo selection http://imgur.com/a/ZT73Y
made some interesting badge type logo's to.

**Comment by TN-1** [comment]
SharkShark-B looks wicked

**Comment by kaptain-kavern** [comment]
SharkShark-B.

**Comment by ILM126** [comment]
Vote: https://www.youtube.com/watch?v=Mh5LY4Mz15o&start=175
(Meant to say, "Vote now on your phones!" If the video doesn't jump)

I vote for SharkShark-B :+1:

**Comment by jameswolff96** [comment]
Was confused because it didn't jump to the timestamp, cool video though.

Also SharkShark-B

**Comment by ILM126** [comment]
@jwolff52 Yeah, I found it a few hours after it was published. Saw it on DiscordApp's Twitter account
Still can't help myself to watch it again XD

**Comment by sharksharkco** [comment]
Hi everyone, thank you for your votes poll is now closed. SharkShark-B it is!
