### ISSUE TITLE
Sunsetting the KerbalStuff-Reborn repo

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock-Project#12]
With the launch of SpaceDock, it is time to sunset this repository, and transfer everything over to the SpaceDock-Project repo.

**Comment by StollD** [comment]
Or we just delete the other one and rename this repo ;)

**Comment by Ristellise** [comment]
Yeah we shoulb.. but move over... a bit difficult

**Comment by ghost** [comment]
@ThomasKerman Welp, I forgot that you could do that. Done. :D
