### ISSUE TITLE
All old downloads

### ISSUE THREAD

**Issue by Ristellise** [KSP-SpaceDock/SpaceDock-Project#17]
I sent the whole chunk of the torrent and put it to github:
_Link removed due to copyright infringements_
For permission I know that some do not allow redistribution but for the sake of the community I have put everything on it git.
You are allowed to have direct link to the zips.

EDIT: if you want me to pull down something tell me.

**Comment by StollD** [comment]
Please take down this repo or prune the mods with restrictive licenses. We don't want to deal with copyright infringements and we respect the licenses of the modders.

That's why I'm removing the link from the text.

**Comment by Ristellise** [comment]
Okay will be remove those that are found in the list.

**Comment by Ristellise** [comment]
UPDATE: took down all those that are in the list. Ready to fix it too..
