### ISSUE TITLE
Title pictures for mods

### ISSUE THREAD

**Issue by RealKolago** [KSP-SpaceDock/SpaceDock-Project#19]
On the old KS site were mod title pictures uploaded by the mod creators. For the moment these are gone. But if you bring back these I have a suggestion:

On KS these pictures were sometimes huge and take a long time to load.
To speed thinks up consider to scale same down to the size needed on the front page.

**Comment by NecroBones** [comment]
We're discussing this over in the KSP-SpaceDock/SpaceDock issues too.

**Comment by Olympic1** [comment]
Moved to KSP-SpaceDock/SpaceDock/issues/25
