### ISSUE TITLE
Flash blocker keeps warning of flash on pages

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock-Project#20]
Some pages seem to trigger my flash blocker.  The last one was the SpaceY Expanded mod page.

Looking at the source, I can find no flash components.    Any ideas what could be triggering this?

The pages with even with flash disabled.

**Comment by NecroBones** [comment]
Maybe imgur albums are causing it? Not sure.

**Comment by StollD** [comment]
If your flash blocker triggers, even with flash disabled, it's not an issue on our end. Closing this one. :wink:
