### ISSUE TITLE
Inconsistent linebreak behavior in mod description text box 

### ISSUE THREAD

**Issue by Aqua-KSP** [KSP-SpaceDock/SpaceDock-Project#23]
When first writing in the description text box there's no automatic linebreak.
https://i.imgur.com/4nGAFjX.png

After setting up other stuff I returned to edit the description again and now there's an automatic linebreak (which doesn't do a good job).
https://i.imgur.com/BcClOZ3.png

Browser: Internet Explorer 11 (11.0.9600.18205)

**Comment by ghost** [comment]
Since the description uses Markdown, and markdown ignores single line breaks, **and** linebreaks in textboxes are browser dependent:

Closed as wontfix.

Please reopen this issue when you have issues with the description as a visitor to your mod's page would see it.
