### ISSUE TITLE
Transfer of Copyrights

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock-Project#24]
I transfer the copyright to all my contributions to the SpaceDock project.

In turn, I want my name removed from official documents (for ex. LICENSE), as I do not want to be associated with a project that is willing to tolerate abusive behavior.

**Comment by NecroBones** [comment]
What happened?

**Comment by ghost** [comment]
I want to protect the guilty, to be honest. I do not want to cause grief. Just want to be done.

**Comment by godarklight** [comment]
http://pastebin.com/uG5ni67A happened. If you want to contribute more than a code of conduct without telling anyone next time, you've very much welcome back with us :)

**Comment by ghost** [comment]
The pull request was sitting around for a couple of days before it got
merged.

**Comment by NecroBones** [comment]
Yeah, it's a prickly situation for sure. I understand both sides of the argument. In other organizations I've been involved with, it's often come down to a sense of "scope" about the purpose of the organization, how members interact with each other, and what the interaction with outsiders will entail. Being a software project, the rules probably need to focus more on how code is contributed and the like. So I dunno. There's probably a happy middle-ground somewhere, I'm just not sure what to suggest. ;)
