### ISSUE TITLE
Spacedock/KS-Reborn Communication methods.

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock-Project#4]
Obviously, here. But we'll need our own means of communication, instead of spamming the CKAN IRC all the time.

~~IRC: TBD~~ esper.net #spacedock is live.

**Comment by StollD** [comment]
I think IRC is all we need. We'll have fluid communication and with some fellow bots we even have tell commands to leave messages to users who are offline at the moment.

**Comment by kaptain-kavern** [comment]
While i was active in the Rimwold modding  Community, we put a _slack.com space_ in place and find it very useful for organisation/communication between modders. I think the whole modding community still continue to use it

Just my 2 cents

---

I have used something [like that](https://levels.io/slack-typeform-auto-invite-sign-ups/) (or [this one](https://github.com/rauchg/slackin)) in order to manage subscriptions, at the tim

**Comment by ghost** [comment]
what's the benefit of slack.com? It looks more like something we could use for team communication, rather than as a channel to talk to users / modders.

**Comment by jkoritzinsky** [comment]
My 2 cents: Slack is amazing.  I use it for one of the orgs I'm in and at my job and I love it. Its mobile clients are really good too.

**Comment by EIREXE** [comment]
I would rather use discord tbh, it's basically a better slack.

**Comment by ILM126** [comment]
@EIREXE So has anyone set up a Discord Server yet? If not, I can do it now.

**Comment by Ristellise** [comment]
@eirexe
Some dont use discord. Slack would be good.
EDIT: personally do not like discord. Dont wanna bog down my computer either.

**Comment by ILM126** [comment]
@Joshwood69 Never used Slack before, but from what I heard. It's close to Discord.

**Comment by Ristellise** [comment]
@ILM126 cannot comfirm but slack is very good. There are integrations and various things among things that you can do with it.

**Comment by Ristellise** [comment]
Slack is also free.

**Comment by ghost** [comment]
Can you give some examples regarding integrations?

@ILM126 as well.

I know nothing about either option.

**Comment by jkoritzinsky** [comment]
Some examples: GitHub commit and pr info. Calendar integration. There's a list here: https://slack.com/apps

-----Original Message-----

**Comment by StollD** [comment]
While Slack and Discord are really nice, we don't need it. IRC can be configured to put out commit and pr info, and it is already there / popular. Also, we are already spamming GitHub with our discussion, as I got 60 emails overnight.

**Comment by ghost** [comment]
VITAS is setting up a mattermost.org instance for us. It's slack, but open source and under our control.

**Comment by kaptain-kavern** [comment]
I don't know that soft. Looks promising ...

**Comment by ILM126** [comment]
@phmayo Oh? Where will it be hosted then?
