### ISSUE TITLE
File Pruning

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock-Project#7]
Prune the files stored and remove non-redistributable mods.

**Comment by StollD** [comment]
With the database file provided by SirCmpwn it should be easy to write a script that removes mods who have a license / puts them into a .txt so that we can inform the authors if they ask.

We shouldn't delete the mods, but keep them unaccessable, so that when the author lost the code, but he gives us his OK, we can reupload it.

**Comment by ghost** [comment]
All right, good idea.

@EIREXE, can you do that as you do #5?

**Comment by EIREXE** [comment]
If you can provide a list of free licenses used in KS yes.

**Comment by ghost** [comment]
https://opensource.org/licenses/alphabetical <- will that work?

**Comment by Olympic1** [comment]
These were the license used by KS
- MIT
- BSD
- GPLv2
- GPLv3
- LGPL
- Other

**Comment by ghost** [comment]
Well, anything with "Other" needs to be dumped. I'll poke at the SQL as well, but on the morrow.

**Comment by NecroBones** [comment]
I'd be hesitant to drop "other". All of my mods (for example) used "other" because they were using Creative Commons, which wasn't in the list. CC is perfectly fine to distribute. I'd rather see a list of what was put in the "other" field and see if we can reasonably filter on that first.

**Comment by ghost** [comment]
That's what I mean. Dumped, rather than pruned. My bad!

**Comment by politas** [comment]
Yeah "Other" would need to drop through to a second-level check for "Creative Commons" or "CC" or "WTFPL" for a start.

**Comment by ghost** [comment]
Indeed. It means human review.

**Comment by NecroBones** [comment]
Whew, glad I misread that. :)

**Comment by ghost** [comment]
:D

**Comment by politas** [comment]
Hopefully the new site can support a more comprehensive list of licences, to standardise the names, if nothing else. The CKAN spec schema has a pretty good list, which would help with integration.

**Comment by inigma2** [comment]
pjf from CKAN has meta data and a list of which mods are re-distributable on his end and he is making those available on CKAN. i recommend Space Dock start with no mods, force authors to re-register and re-upload. Start fresh. Or else we'll have a mess on our hands.

**Comment by ghost** [comment]
We have some data available: We can map (at least some) forum usernames to (all) uploaded mods, and their respective licenses.

I'll commit a CSV containing this data Shortly(tm).

**Comment by ghost** [comment]
Commit 68bf7b4
