### ISSUE TITLE
Website Offline!

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock-Project#9]
We are in the homestretch, working out the kinks in the front end.

As soon as we are ready to go public, we will Close this issue, and we can focus on improving the site, and worry about getting redundant infrastructure going.
# To be done:
- [x] get user reg working
- [X] get mod up/dl working

**Comment by EIREXE** [comment]
Doesn't mod upload work already? as far as i know it's not disabled in the source code.

**Comment by ghost** [comment]
Dotting is, crossing ts.

**Comment by inigma2** [comment]
Nearly ready to launch. Fixing up little things. Turning on lights. Listening to the hum of the engine. Drawing straws for various items. Ordering champagne. Readying our minds to receive bug reports.

**Comment by ghost** [comment]
And we are go.
